version: "3.7"

services:
  neovim_ide:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        GIT_USER_NAME: "Ravil Fayrushin"
        GIT_USER_EMAIL: "ravil.fayrushin@gmail.com"
    volumes:
      - $HOME/.ssh:$HOME/.ssh
    environment:
      UID:
      GID:
